spring.application.name=carsdealer

# MySQL config (sử dụng biến môi trường từ Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cloudinary config
cloudinary.url=cloudinary://789858934897389:95g58S6_QXn8lxCePe2Pn1rTjpc@dwikvcatv

# Server config
server.port=8080

# Static resources
spring.web.resources.static-locations=classpath:/static/

# Thymeleaf config
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# File upload config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
