
spring.application.name=carsdealer


spring.datasource.url=jdbc:mysql://localhost:3306/forddb
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

cloudinary.url=cloudinary://789858934897389:95g58S6_QXn8lxCePe2Pn1rTjpc@dwikvcatv

server.port=8081
spring.data.mongodb.uri=mongodb+srv://nhoxphu2005_db_user:FT5Fqn6YZS0XK4mY@web.abcd.mongodb.net/forddb?retryWrites=true&w=majority
spring.data.mongodb.database=forddb


spring.web.resources.static-locations=classpath:/static/


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
